<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Authors>Wilderness Labs, Inc</Authors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <LangVersion>12</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/</PackageProjectUrl>
    <PackageId>Meadow.Modbus</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Modbus</RepositoryUrl>
    <PackageTags>Meadow, Modbus</PackageTags>
    <Description>Wilderness Labs .NET Library supporting Modbus RTU Client, Modbus TCP Client and Modbus TCP server.</Description>
    <AssemblyVersion>0.28.0</AssemblyVersion>
    <FileVersion>0.28.0</FileVersion>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <NoWarn>CS8597;CS8600;CS8601;CS8602;CS8603;CS8604;CS8605;CS8612;CS8618;CS8619;CS8622;CS8714;CS8765;CS8767</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="" />
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Meadow.Contracts\Source\Meadow.Contracts\Meadow.Contracts.csproj" />
  </ItemGroup>
</Project>
